apiVersion: kvc.kubeflow.org/v1
kind: VolumeManager
metadata:
  name: kvc-example1
  namespace: <insert-namespace-here>
spec:
  volumeConfigs:
    - id: "vol1"
      replicas: 1
      sourceType: "Pachyderm"
      accessMode: "ReadWriteOnce"
      capacity: 5Gi
      labels:
        key1: val1
        key2: val2
      options:
        repo: <insert-repo-here>
        branch: <insert-branch-here>
        filePath: <insert-filepath-here>
        # recursive: false
        # dataPath: <insert-data-path-here-optional>"
