apiVersion: vck.intelai.org/v1
kind: VolumeManager
metadata:
  name: vck-example1
  namespace: <insert-namespace-here>
spec:
  volumeConfigs:
    - id: "vol1"
      replicas: 1
      sourceType: "S3"
      accessMode: "ReadWriteOnce"
      nodeAffinity:
        - <insert-node-affinity-here>
      tolerations:
        - <insert-tolerations-here>
      capacity: 5Gi
      labels:
        key1: val1
        key2: val2
      options:
        awsCredentialsSecretName: <insert-secret-name-for-aws-credentials>
        sourceURL: "s3://neon-stockdatasets/cifar-100-python.tar.gz"
        # dataPath: <insert-data-path-here-optional>"
        # distributionStrategy: <insert-distributed-strategy-here-optional>
