apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vck
  namespace: {{ .Values.namespace }}
  labels:
    app: vck
    servicetype: controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vck
        servicetype: controller
    spec:
      serviceAccountName: vck
      containers:
      - name: vck
        image: {{ .Values.registry }}{{ .Values.org }}/{{ .Values.repo }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - "/vck"
          {{- range .Values.flags }}
          - {{ . | quote }}
          {{- end }}
          {{- if .Values.log_level }}
          - "--v={{ .Values.log_level }}"
          {{- end }}
          - {{ required "valid namespace required" .Values.namespace | printf "--namespace=%s" | quote }}
