apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kvc
  namespace: {{ .Values.namespace }}
  labels:
    app: kvc
    servicetype: controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kvc
        servicetype: controller
    spec:
      serviceAccountName: kvc
      containers:
      - name: kvc
        image: {{ .Values.registry }}{{ .Values.org }}/{{ .Values.repo }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - "/kvc"
          {{- range .Values.flags }}
          - {{ . | quote }}
          {{- end }}
          {{- if .Values.log_level }}
          - "--v={{ .Values.log_level }}"
          {{- end }}
          - {{ required "valid namespace required" .Values.namespace | printf "--namespace=%s" | quote }}
