{{- if .Values.crd.install -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumemanagers.vck.intelai.org
spec:
  group: vck.intelai.org
  names:
    kind: VolumeManager
    listKind: VolumeManagerList
    plural: volumemanagers
    singular: volumemanager
  scope: Namespaced
  version: v1alpha1
{{end}}
