{{- if .Values.clusterrole.install -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kvc
  labels:
    app: kvc
rules:
- apiGroups:
  - kvc.kubeflow.org
  resources:
  - volumemanagers
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/log
  - services
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - events
  - nodes
  verbs:
  - "*"
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - "*"
---
{{ end }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kvc-{{ .Release.Name }}
  labels:
    app: kvc
subjects:
- kind: ServiceAccount
  name: kvc
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kvc
