{{- if .Values.webhook.install -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: validation-webhook
  namespace: {{ .Values.namespace }}
  labels:
    app: validation-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: webhook
        app: validation-webhook
    spec:
      containers:
      - name: validation-webhook
        image: {{ .Values.registry }}{{ .Values.org }}/{{ .Values.repo }}:{{ .Values.tag }}
        imagePullPolicy: IfNotPresent
        args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
        command:
          - "/validation-webhook"
        volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: validation-webhook-cert
{{end}}
