apiVersion: v1
kind: Pod
metadata:
  name: vck-claim-pod
spec:
  affinity:
    <insert-node-affinity-from-cr-status>
  volumes:
    - name: dataset-claim
      <insert-volume-source-from-cr-status>
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 1d"]
    name: vck-sleep
    volumeMounts:
    - mountPath: /var/data
      name: dataset-claim
